name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm run build
      - name: Deploy
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DEPLOY_PASSWORD: ${{ secrets.SSH_PRIVATE_KEY }}  # Referencing the secret
        run: |
          echo "$DEPLOY_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'sudo -S cp -r /path/to/dist/* /var/www/html'
