name: Deploy Vue Project

on:
  push:
    branches:
      - main  # Deploys on push to the main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Ensure this runs on your self-hosted runner

    steps:
      # Step 1: Checkout the repository with SSH key
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust to your Node version

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Copy build to server directory
        run: |
          sudo mkdir -p /var/www/html/portfolio
          ls
          cp -r .output/* /var/www/portfolio/
          cd /var/www/portfolio/
          pm2 delete 0
          pm2 start server/index.mjs
