name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        eval "$(ssh-agent -s)"
        ssh-add private_key
        mkdir -p ~/.ssh
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

    - name: Build the project
      run: |
        npm install
        npm run build

    - name: Copy files to server
      run: |
        scp -o LogLevel=DEBUG -r dist/* gh-actions@$SSH_HOST:/var/www/html/portfolio
