name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy files to VPS
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }} # Add the password secret here
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          git clone https://github.com/rodlessa/vite-portfolio.git
