name: Deploy Vue Project

on:
  push:
    branches:
      - main  # Deploys on push to the main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your required Node version

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 4: Copy build to remote server
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          # Ensure .ssh directory exists
          mkdir -p ~/.ssh

          # Add server to known hosts
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          
          # Save the private key and set permissions
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Use rsync to copy files to the remote server
          rsync -avz -e "ssh -i ~/.ssh/deploy_key" dist/ $SSH_USER@$SSH_HOST:/var/www/html/

          # Cleanup private key after use
          rm -f ~/.ssh/deploy_key
