name: Deploy Vue Project

on:
  push:
    branches:
      - main  # Deploys on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust to your Node version

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 4: Deploy to remote server via SSH
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$SSH_HOST << 'EOF'
            sudo mkdir -p /var/www/html/portfolio
            sudo cp -r /path/to/local/build/* /var/www/html/portfolio/
            cd /var/www/html/portfolio/
            pm2 describe 0 >/dev/null && pm2 delete 0 || echo "No process with ID 0 to delete"
            pm2 start server/index.mjs
          EOF
          rm private_key.pem
