name: Deploy Vue Project

on:
  push:
    branches:
      - main  # Deploys on push to the main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Make sure this runs on your self-hosted runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your required Node version

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm ci  # Use npm ci for faster installs in CI environments
          npm run build

      # Step 4: Deploy build to server
      - name: Copy build to server directory
        run: |
          sudo mkdir -p /var/www/html/portfolio
          sudo rm -rf /var/www/html/portfolio/*
          sudo cp -r .output/* /var/www/html/portfolio/

      # Step 5: Restart server using PM2
      - name: Restart server using PM2
        env:
          NODE_ENV: production
        run: |
          sudo pm2 start /var/www/html/portfolio/server/index.mjs --name portfolio
          sudo pm2 save
    